module.exports = {
  vi: {
    about: 'Giới thiệu bản thân',
    skills: 'Kỹ năng',
    projects: 'Dự án',
    education: 'Học vấn',
    achievements: 'Thành tích',
    certifications: 'Chứng chỉ',
    career_goals: 'Mục tiêu nghề nghiệp',
    download_cv: 'Tải CV',
    contact: 'Liên hệ',
    phone_tooltip: 'Chỉ hỗ trợ gọi trên điện thoại',
    email_tooltip: 'Click để gửi email',
    location: 'Địa chỉ',
    birthday: 'Ngày sinh',
    university: 'Trường đại học',
    ba_tagline: 'Lập trình viên Backend & Chuyên viên phân tích nghiệp vụ',
  },
  en: {
    about: 'About Me',
    skills: 'Skills',
    projects: 'Projects',
    education: 'Education',
    achievements: 'Achievements',
    certifications: 'Certifications',
    career_goals: 'Career Goals',
    download_cv: 'Download CV',
    contact: 'Contact',
    phone_tooltip: 'Only supported on mobile',
    email_tooltip: 'Click to send email',
    location: 'Location',
    birthday: 'Birthday',
    university: 'University',
    ba_tagline: 'Backend Developer & Business Analyst',
  }
}; 